os: linux
language: cpp
jdk:
  - oraclejdk8
env:
  global:
    - DATADIR=$HOME/.bitcoin
    - RESULTDIR=$HOME/results
    - RPC_TESTS_GIT_URL=https://github.com/dexX7/mastercore-rpc-tests.git
    - SPOCK_TESTS_GIT_URL=https://github.com/msgilligan/bitcoin-spock.git
    - JAVA_COMPARISON_TOOL_URL=https://github.com/TheBlueMatt/test-scripts/blob/38b490a2599d422b12d5ce8f165792f63fd8f54f/pull-tests-0f7b5d8.jar?raw=true
    - JAVA_COMPARISON_TOOL_HASH=ecd43b988a8b673b483e4f69f931596360a5e90fc415c75c4c259faa690df198
cache:
  apt: true
matrix:
  fast_finish: true
before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libtool
  - sudo apt-get install -y autotools-dev
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libboost1.55-all-dev
  - sudo apt-get install -y libdb4.8-dev
  - sudo apt-get install -y libdb4.8++-dev
  - sudo apt-get install -y libqt4-dev
  - sudo apt-get install -y libprotobuf-dev
  - sudo apt-get install -y protobuf-compiler
  - sudo apt-get install -y libqrencode-dev
  - sudo apt-get install -y lcov
  - sudo pip install cpp-coveralls
install:
  - ./autogen.sh
  - ./configure --disable-dependency-tracking --enable-lcov
  - make -j 3
before_script:
  - cp ./src/mastercored ./src/bitcoind
  - cp ./src/mastercore-cli ./src/bitcoin-cli
  - mkdir -p $RESULTDIR
script:
  - make check
  - make cov
after_success:
  - coveralls --gcov-options '\-lp'
