os: linux
language: cpp
env:
  global:
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - MASTERCORED=$TRAVIS_BUILD_DIR/src/mastercored
    - MASTERCORECLI=$TRAVIS_BUILD_DIR/src/mastercore-cli
cache:
  apt: true
  directories:
  - $HOME/.ccache
matrix:
  fast_finish: true
before_install:
  - sudo add-apt-repository ppa:apokluda/boost1.53 -y
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libtool autotools-dev autoconf
  - sudo apt-get install -y ccache
  - ccache --max-size=$CCACHE_SIZE
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export CCACHE_READONLY=1; fi
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libboost1.53-all-dev
  - sudo apt-get install -y libdb4.8-dev
  - sudo apt-get install -y libdb4.8++-dev
  - sudo apt-get install -y libqt4-dev libprotobuf-dev protobuf-compiler
  - sudo apt-get install -y libqrencode-dev
install:
  - ./autogen.sh
  - ./configure --cache-file=config.cache --disable-dependency-tracking
  - make
before_script:
  - cd qa/
  - git clone git://github.com/dexX7/mastercore-rpc-tests.git mastercore-rpc-tests
  - cd ..
script:
  - ./src/test/test_bitcoin
  - ./src/qt/test/test_bitcoin-qt
  - python2 ./qa/mastercore-rpc-tests/test_exodus_purchase.py
  - python2 ./qa/mastercore-rpc-tests/test_traditional_dex.py
  - python2 ./qa/mastercore-rpc-tests/test_property_creation.py
  - python2 ./qa/mastercore-rpc-tests/test_p2sh.py
